name: scraper

on:
    workflow_dispatch:
    schedule:
        - cron: "*/5 * * * *" # runs every fifth minute

jobs:
    generate_list:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v3

            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: install python packages and other dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install ghostscript python3-tk -y
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: execute py script
              run: python scraper.py

            - name: create adblocking lists
              run: |
                  sed 's/^/\|\|/;s/$/\^/' blocklist.txt > blocklist_ABP.txt
                  sed 's/^/\|\|/;s/$/\^$all/' blocklist.txt > blocklist_UBO.txt

            - name: commit files
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A
                  git diff --name-only --cached --exit-code || ( git commit -am "update blocklist" && git push )
